[workspace]
resolver = "3"
members = [
    "crates/elf-eater-analyzer",
    "crates/elf-eater-cli", "crates/generate-call-tree",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.94"
authors = [
    "Varov Svyatoslav <slava-varov3@mail.ru>",
]
repository = "https://www.github.com/hack3rmann/elf-eater"

[workspace.dependencies]
elf-eater-analyzer = { path = "crates/elf-eater-analyzer" }
elf-eater-cli = { path = "crates/elf-eater-cli" }
goblin = "0.10.5"
iced-x86 = "1.21.0"
smallvec = { version = "1.15.1", features = ["union", "const_generics", "const_new"] }
petgraph = { version = "0.8.3", features = ["std"] }
bitflags = "2.11.1"
clap = { version = "4.6.1", features = ["derive"] }
